#!/bin/sh

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >> "$zshrc"
    else
      printf "\\n%s\\n" "$text" >> "$zshrc"
    fi
  fi
}

link_dotfile() {
  if [ -L "$HOME/.$1" ] && [ ! -a "HOME/.$1" ]; then
    rm "$HOME/.$1"
  fi

  if [ -e "$HOME/.$1" ] && [ ! -L "$HOME/.$1" ]; then
    echo "File already exists at $HOME/.$1 I will back it up for you..."
    mv "$HOME/.$1"{,.link.backup}
    echo "$HOME/.$1.link.backup created"
  fi

  echo "Linking $1"
  ln -sf "$DIR/$1" "$HOME/.$1"
}

fancy_echo() {
  local fmt="$1"; shift
  printf "\\n$fmt\\n" "$@"
}

install_nvm() {
  mkdir "$HOME/.nvm"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
  nvm --install lts stable
  nvm alias default stable
}

install_os_specific_packages() {
  if [ -f "os/$OSTYPE" ]; then
    source "os/$OSTYPE"
  fi
}

install_vim_plug() {
  if [ ! -d "$HOME/.nvm" ]; then
    fancy_echo "Installing Node ..."
    install_nvm
  fi
}

update_shell() {
  local shell_path;
  shell_path="$(command -v zsh)"

  fancy_echo "Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    fancy_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

fancy_echo "Installing OS Specific Packages ..."
install_os_specific_packages

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

link_dotfile gitconfig
link_dotfile zshrc
link_dotfile psqlrc
link_dotfile gitmessage

if [ ! -d "$HOME/.nvm" ]; then
  fancy_echo "Installing Node ..."
  install_nvm
fi
