#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >> "$zshrc"
    else
      printf "\\n%s\\n" "$text" >> "$zshrc"
    fi
  fi
}

link_dotfile() {
  if [ -L "$HOME/.$1" ] && [ ! -a "HOME/.$1" ]; then
    rm "$HOME/.$1"
  fi

  if [ -e "$HOME/.$1" ] && [ ! -L "$HOME/.$1" ]; then
    echo "File already exists at $HOME/.$1 I will back it up for you..."
    mv "$HOME/.$1"{,.link.backup}
    echo "$HOME/.$1.link.backup created"
  fi

  echo "Linking $1"
  ln -sf "$DIR/$1" "$HOME/.$1"
}

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

load_nvm() {
  export NVM_DIR="$HOME/.nvm"
  # shellcheck source=/dev/null
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
}

install_nvm() {
  if [ ! -d "$HOME/.nvm" ]; then
    fancy_echo "Installing Node ..."
    mkdir "$HOME/.nvm"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
    load_nvm
    nvm install --lts stable
    nvm alias default stable
  fi
}

install_os_specific_packages() {
  if [[ "$OSTYPE" == "linux-gnu" ]]; then
    OS=linux
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    OS=mac
  fi
  if [ -f "os/$OS" ]; then
    # shellcheck source=/dev/null
    source "os/$OS"
  fi
}

install_vim_plug() {
  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi
}

vim_up() {
  VIM_INSTALL_PHASE=1 vim -u "$HOME"/.vimrc +PlugUpdate +PlugClean! +qa
}

update_shell() {
  local shell_path;
  shell_path="$(command -v zsh)"

  if [ -n "$USER" ]; then
    fancy_echo "Changing your shell to zsh ..."
    if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
      fancy_echo "Adding '$shell_path' to /etc/shells"
      sudo sh -c "echo $shell_path >> /etc/shells"
    fi

    sudo chsh -s "$shell_path" "$USER"
  fi
}

link_dotfile gitconfig
link_dotfile zshrc
link_dotfile psqlrc
link_dotfile gitmessage
link_dotfile gitignore
link_dotfile vimrc

fancy_echo "Installing OS Specific Packages ..."
install_os_specific_packages
install_vim_plug
vim_up

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

if [ ! -d "$HOME/.nvm" ]; then
  fancy_echo "Installing Node ..."
  install_nvm
fi


fancy_echo "===========================================================\\n"
echo "Installation and Dotfiles have been completed successfully!"
echo "If this is your first time running this script, please reboot"
echo "your computer now. Enjoy the setup :)"
fancy_echo "For more information about your new setup see:"
echo "https://github.com/Shift3/laptop/blob/master/README.md"
fancy_echo "==========================================================="
