version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: brew update
      - run: brew install shellcheck
      - run: shellcheck setup -e SC2039
      - run: sh setup
