version: 2
jobs:
  test-mac:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: brew update
      - run: brew install shellcheck
      - run: shellcheck setup -e SC2039
      - run: sh setup
  test-ubuntu:
    docker:
      - image: ubuntu:disco
    steps:
      - checkout
      - run: apt update
      - run: apt install -y shellcheck
      - run: shellcheck setup -e SC2039
      - run: sh setup
  test-fedora:
    docker:
      - image: fedora:31
    steps:
      - checkout
      - run: dnf -y install ShellCheck
      - run: shellcheck setup -e SC2039
      - run: sh setup

workflows:
  version: 2
  test-all:
    jobs:
      - test-mac
      - test-ubuntu
      - test-fedora
