version: 2
jobs:
  test-mac:
    macos:
      xcode: 12.3.0
    steps:
      - checkout
      - run: brew update
      - run: brew install shellcheck
      - run: shellcheck setup -e SC2039 -e SC1091
      - run:
          environment:
            AWS_ACCESS_KEY_ID: example
            AWS_SECRET_ACCESS_KEY: example
            AWS_DEFAULT_REGION: us-east-1
          name: Run Setup Script
          command: ./setup
          no_output_timeout: 30m
  test-ubuntu:
    docker:
      - image: ubuntu:22.04
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: America/Los_Angeles
    steps:
      - checkout
      - run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      - run: apt update
      - run: apt install -y shellcheck sudo
      - run: shellcheck setup -e SC2039 -e SC1091
      - run: 
          environment:
            AWS_ACCESS_KEY_ID: example
            AWS_SECRET_ACCESS_KEY: example
            AWS_DEFAULT_REGION: us-east-1
          command: ./setup
  test-fedora:
    docker:
      - image: fedora:33
    steps:
      - checkout
      - run: dnf -y install ShellCheck sudo util-linux-user
      - run: shellcheck setup -e SC2039 -e SC1091
      - run: 
          environment:
            AWS_ACCESS_KEY_ID: example
            AWS_SECRET_ACCESS_KEY: example
            AWS_DEFAULT_REGION: us-east-1
          command: ./setup

workflows:
  version: 2
  test-all:
    jobs:
      - test-mac
      - test-ubuntu
      - test-fedora
