version: 2
jobs:
  test-mac:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: brew update
      - run: brew install shellcheck
      - run: shellcheck setup -e SC2039
      - run: ./setup
  test-ubuntu:
    docker:
      - image: ubuntu:19.04
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: America/Los_Angeles
    steps:
      - checkout
      - run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      - run: apt update
      - run: apt install -y shellcheck sudo
      - run: shellcheck setup -e SC2039
      - run: ./setup
  test-fedora:
    docker:
      - image: fedora:31
    steps:
      - checkout
      - run: dnf -y install ShellCheck sudo util-linux-user
      - run: shellcheck setup -e SC2039
      - run: ./setup

workflows:
  version: 2
  test-all:
    jobs:
      - test-mac
      - test-ubuntu
      - test-fedora
