#!/bin/bash

OS=
RELEASE=$(cat /etc/*release | grep ^NAME)
ID_LIKE=$(cat /etc/*release | grep "^ID_LIKE=")
ID=$(cat /etc/*release | grep "^ID=")

if grep -q Fedora <<< $RELEASE; then
    OS=Fedora
elif grep -q -i ubuntu <<< $ID || grep -q -i ubuntu <<< $ID_LIKE; then
    OS=Debian
    DOCKER_APT_REPO="deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        bionic stable"
    MONGO_APT_REPO="deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu \
        bionic/mongodb-org/4.2 multiverse"
elif grep -q -i debian <<< $ID || grep -q -i debian <<< $ID_LIKE; then
    OS=Debian
    DOCKER_APT_REPO="deb [arch=amd64] https://download.docker.com/linux/debian \
        buster stable"
    MONGO_APT_REPO="deb http://repo.mongodb.org/apt/debian \
        buster/mongodb-org/4.2 main"
fi

SHARED_PACKAGES=$(cat <<EOF
curl git zsh vim tmux httpie vim hub

mongodb-org
EOF
)

DEBIAN_PACKAGES=$(cat <<EOF
$SHARED_PACKAGES
build-essential

postgresql redis-server
imagemagick shellcheck gnupg
silversearcher-ag
EOF
)

FEDORA_PACKAGES=$(cat <<EOF
$SHARED_PACKAGES

util-linux-user
git-lfs the_silver_searcher
ShellCheck ImageMagick
postgresql-server postgresql-contrib libpq-devel redis

dnf-plugins-core

openssl-devel
EOF
)

fedora_enable_databases_on_restart() {
    fancy_echo "Ensuring databases run on startup."
    if sudo bash -c '[ ! -d "/var/lib/pgsql/data" ]'; then
        sudo /usr/bin/postgresql-setup --initdb
    fi
    sudo systemctl enable postgresql
    sudo systemctl enable redis
    sudo systemctl enable mongod
}

debian_enable_databases_on_restart() {
    fancy_echo "Ensuring databases run on startup."
    sudo systemctl enable postgresql
    sudo systemctl enable redis-server
    sudo systemctl enable mongod
}

apt_add_mongo_repo() {
    echo "$MONGO_APT_REPO" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
    sudo apt install -y -q gnupg wget
    wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
    sudo apt-get update
}

dnf_add_mongo_repo() {
    sudo tee /etc/yum.repos.d/mongodb-org-4.2.repo > /dev/null <<EOF
[mongodb-org-4.2]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.2/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc
EOF
}

dnf_add_and_install_docker_ce() {
    sudo dnf config-manager \
        --add-repo \
        https://download.docker.com/linux/fedora/docker-ce.repo
    sudo dnf -y install docker-ce docker-ce-cli containerd.io
}

deb_add_and_install_docker_ce() {
    sudo apt install -y -q \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    sudo add-apt-repository "$DOCKER_APT_REPO"
    sudo apt-get update
    sudo apt-get install -y -q docker-ce docker-ce-cli containerd.io
}

systemd_enable_docker_on_restart() {
    fancy_echo "Ensuring Docker runs on startup."
    sudo usermod -aG docker $(whoami)
    sudo systemctl enable docker
}

install_circleci_cli() {
    curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
}

deb_add_and_install_terraform() {
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt-get install -y terraform
}

dnf_add_and_install_terraform() {
    sudo dnf install -y dnf-plugins-core
    sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/$release/hashicorp.repo
    sudo dnf -y install terraform
}

case $OS in
    Fedora)
        fancy_echo "Installing packages using dnf"
        sudo dnf groupinstall -y "C Development Tools and Libraries"
        dnf_add_mongo_repo
        dnf_add_and_install_terraform
        sudo dnf -y install $FEDORA_PACKAGES
        install_circleci_cli
        fedora_enable_databases_on_restart
        ;;
    Debian)
        fancy_echo "Installing packages using apt"
        deb_add_and_install_docker_ce
        deb_add_and_install_terraform
        apt_add_mongo_repo
        sudo apt install -y -q $DEBIAN_PACKAGES
        install_circleci_cli
        debian_enable_databases_on_restart
        systemd_enable_docker_on_restart
        ;;
    *)
        fancy_echo "You're OS is not detected, cannot install packages."
        exit 1
        ;;
esac
