#!/bin/bash

OS=
RELEASE=$(cat /etc/*release | grep ^NAME)

if grep -q Fedora <<< $RELEASE; then
    OS=Fedora
elif grep -q Ubuntu <<< $RELEASE; then
    OS=Debian
    DOCKER_APT_REPO="deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
    MONGO_APT_REPO="deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu \
        bionic/mongodb-org/4.2 multiverse"
elif grep -q Debian <<< $RELEASE; then
    OS=Debian
    DOCKER_APT_REPO="deb [arch=amd64] https://download.docker.com/linux/debian \
        $(lsb_release -cs) \
        stable"
    MONGO_APT_REPO="deb http://repo.mongodb.org/apt/debian \
        buster/mongodb-org/4.2 main"
fi

SHARED_PACKAGES=$(cat <<EOF
curl git zsh vim tmux httpie vim hub

mongodb-org
EOF
)

DEBIAN_PACKAGES=$(cat <<EOF
$SHARED_PACKAGES
build-essential

imagemagick shellcheck gnupg
silversearcher-ag shellcheck
EOF
)

FEDORA_PACKAGES=$(cat <<EOF
$SHARED_PACKAGES

git-lfs the_silver_searcher 
ShellCheck ImageMagick
postgresql-server postgresql-contrib libpq-devel redis

dnf-plugins-core

openssl-devel
EOF
)

systemd_enable_databases_on_restart() {
    fancy_echo "Ensuring databases run on startup."
    if sudo bash -c '[ ! -d "/var/lib/pgsql/data" ]'; then
        sudo /usr/bin/postgresql-setup --initdb
    fi
    sudo service postgresql start
    sudo service redis start
    sudo service mongod start
    sudo systemctl enable postgresql
    sudo systemctl enable redis
    sudo systemctl enable mongod
}

apt_add_mongo_repo() {
    echo $DOCKER_APT_REPO | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
    sudo apt-get update
}

dnf_add_mongo_repo() {
    sudo tee /etc/yum.repos.d/mongodb-org-4.2.repo > /dev/null <<EOF
[mongodb-org-4.2]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.2/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc
EOF
}

dnf_add_and_install_docker_ce() {
    sudo dnf config-manager \
        --add-repo \
        https://download.docker.com/linux/fedora/docker-ce.repo
    sudo dnf -y install docker-ce docker-ce-cli containerd.io
}

deb_add_and_install_docker_ce() {
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    sudo add-apt-repository $DOCKER_APT_REPO
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io
}

systemd_enable_docker_on_restart() {
    fancy_echo "Ensuring Docker runs on startup."
    sudo usermod -aG docker $(whoami)
    sudo service docker start
    sudo systemctl enable docker
}

case $OS in
    Fedora)
        fancy_echo "Installing packages using dnf"
        sudo dnf groupinstall -y "C Development Tools and Libraries"
        dnf_add_mongo_repo
        sudo dnf -y install $FEDORA_PACKAGES
        dnf_add_and_install_docker_ce
        systemd_enable_databases_on_restart
        systemd_enable_docker_on_restart
        ;;
    Debian)
        fancy_echo "Installing packages using apt"
        apt_add_mongo_repo
        sudo apt install -y $DEBIAN_PACKAGES
        deb_add_and_install_docker_ce
        systemd_enable_databases_on_restart
        systemd_enable_docker_on_restart
        ;;
    *)
        fancy_echo "You're OS is not detected, cannot install packages."
        exit 1
        ;;
esac
