#!/bin/bash
HOMEBREW_PREFIX="/usr/local"

fix_zsh_permissions() {
    # With Mac OS Version >= 10.15.4 seems like fixing directory permissions is
    # necessary.
    # See: https://github.com/Shift3/laptop/issues/11
    if [ -d $HOMEBREW_PREFIX/share/zsh ]; then
        sudo chmod -R 755 $HOMEBREW_PREFIX/share/zsh
        sudo chown -R root:staff $HOMEBREW_PREFIX/share/zsh
    fi
}

install_homebrew() {
  if ! command -v brew >/dev/null; then
    fancy_echo "Installing Homebrew ..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    export PATH="/usr/local/bin:$PATH"
  fi
}

install_homebrew

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151

brew bundle --file=- <<EOF
tap "homebrew/services"
tap "mongodb/brew"

# Unix
brew "git"
brew "openssl"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watchman"
brew "zsh"

# GitHub
brew "hub"

# Docker
cask "docker", args: { force: true }

# Image manipulation
brew "imagemagick"

# Programming language prerequisites and package managers
brew "libyaml" # should come after openssl
brew "coreutils"
brew "yarn"
cask "gpg-suite"

# Databases
brew "postgres", restart_service: :changed
brew "redis", restart_service: :changed
brew "mongodb-community", restart_service: :changed
EOF

fix_zsh_permissions
